/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_api_v1_auth_verify_email_resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Password Reset */
        post: operations["request_password_reset_api_v1_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Password Reset */
        post: operations["confirm_password_reset_api_v1_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_api_v1_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_api_v1_exercises__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Patterns */
        get: operations["list_patterns_api_v1_patterns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patterns/{code}/ladder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ladder */
        get: operations["get_ladder_api_v1_patterns__code__ladder_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Equipment */
        get: operations["list_equipment_api_v1_equipment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_api_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_v1_profile_patch"];
        trace?: never;
    };
    "/api/v1/profile/disclaimer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Disclaimer */
        post: operations["accept_disclaimer_api_v1_profile_disclaimer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/assessment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assess */
        post: operations["assess_api_v1_profile_assessment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/pattern-levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pattern Levels */
        get: operations["list_pattern_levels_api_v1_profile_pattern_levels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Pattern Levels */
        patch: operations["update_pattern_levels_api_v1_profile_pattern_levels_patch"];
        trace?: never;
    };
    "/api/v1/profile/onboarding/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Onboarding */
        post: operations["complete_onboarding_api_v1_profile_onboarding_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_v1_locations_get"];
        put?: never;
        /** Create Location */
        post: operations["create_location_api_v1_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Location */
        delete: operations["delete_location_api_v1_locations__location_id__delete"];
        options?: never;
        head?: never;
        /** Update Location */
        patch: operations["update_location_api_v1_locations__location_id__patch"];
        trace?: never;
    };
    "/api/v1/locations/{location_id}/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace Equipment */
        put: operations["replace_equipment_api_v1_locations__location_id__equipment_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{location_id}/weight-grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weight Grid */
        get: operations["weight_grid_api_v1_locations__location_id__weight_grid_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{location_id}/plates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plates */
        post: operations["plates_api_v1_locations__location_id__plates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Program
         * @description Build a program without saving it, for the «here's what you'd get» screen.
         */
        post: operations["preview_program_api_v1_programs_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Program */
        post: operations["create_program_api_v1_programs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Program */
        get: operations["active_program_api_v1_programs_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program */
        get: operations["get_program_api_v1_programs__program_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssessmentRead */
        AssessmentRead: {
            overall: components["schemas"]["Overall"];
            guidance_level: components["schemas"]["GuidanceLevel"];
            /** Levels */
            levels: components["schemas"]["PatternLevelRead"][];
        };
        /** AssessmentRequest */
        AssessmentRequest: {
            pushups: components["schemas"]["Pushups"];
            pullups: components["schemas"]["Pullups"];
            squats: components["schemas"]["Squats"];
            pistol: components["schemas"]["Pistol"];
            /** Experienced */
            experienced: boolean;
            /** Knows Terms */
            knows_terms: boolean;
            /**
             * Shift
             * @default 0
             * @enum {integer}
             */
            shift?: -1 | 0 | 1;
        };
        /**
         * AssessmentSource
         * @enum {string}
         */
        AssessmentSource: "onboarding" | "performance" | "manual";
        /**
         * BandResistance
         * @enum {string}
         */
        BandResistance: "light" | "medium" | "heavy";
        /**
         * BlockKind
         * @enum {string}
         */
        BlockKind: "warmup" | "main" | "accessory" | "finisher" | "cooldown";
        /** BlockRead */
        BlockRead: {
            kind: components["schemas"]["BlockKind"];
            /** Minutes */
            minutes: number;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["PlannedExerciseRead"][];
        };
        /** Constraints */
        "Constraints-Input": {
            /**
             * Quiet Mode
             * @default false
             */
            quiet_mode?: boolean;
            /**
             * Low Ceiling
             * @default false
             */
            low_ceiling?: boolean;
            /**
             * Limited Space
             * @default false
             */
            limited_space?: boolean;
            surface?: components["schemas"]["Surface"] | null;
        };
        /** Constraints */
        "Constraints-Output": {
            /**
             * Quiet Mode
             * @default false
             */
            quiet_mode: boolean;
            /**
             * Low Ceiling
             * @default false
             */
            low_ceiling: boolean;
            /**
             * Limited Space
             * @default false
             */
            limited_space: boolean;
            surface: components["schemas"]["Surface"] | null;
        };
        /**
         * DisclaimerRequest
         * @description Start-up health screen. The answers only decide the recommendation; they aren't stored.
         */
        DisclaimerRequest: {
            /** Birth Year */
            birth_year: number;
            /** Heart Condition */
            heart_condition: boolean;
            /** Pregnancy */
            pregnancy: boolean;
            /** Recent Injury */
            recent_injury: boolean;
            /**
             * Health Flags
             * @default []
             */
            health_flags?: components["schemas"]["HealthTag"][];
            /**
             * Accepted
             * @constant
             */
            accepted: true;
        };
        /**
         * EquipmentCategory
         * @enum {string}
         */
        EquipmentCategory: "weights" | "bars" | "bands" | "bench" | "support" | "bodyweight";
        /**
         * EquipmentDetails
         * @description `fixed`: weights_kg, one entry per piece (two 16 kg bells → [16, 16]).
         *     `adjustable`: bar_kg + plates. Bands: resistances. Everything else: empty.
         */
        "EquipmentDetails-Input": {
            /** Type */
            type?: ("fixed" | "adjustable") | null;
            /**
             * Weights Kg
             * @default []
             */
            weights_kg?: (number | string)[];
            /** Bar Kg */
            bar_kg?: number | string | null;
            /**
             * Plates
             * @default []
             */
            plates?: components["schemas"]["PlateSet-Input"][];
            /**
             * Resistances
             * @default []
             */
            resistances?: components["schemas"]["BandResistance"][];
        };
        /**
         * EquipmentDetails
         * @description `fixed`: weights_kg, one entry per piece (two 16 kg bells → [16, 16]).
         *     `adjustable`: bar_kg + plates. Bands: resistances. Everything else: empty.
         */
        "EquipmentDetails-Output": {
            /** Type */
            type: ("fixed" | "adjustable") | null;
            /**
             * Weights Kg
             * @default []
             */
            weights_kg: string[];
            /** Bar Kg */
            bar_kg: string | null;
            /**
             * Plates
             * @default []
             */
            plates: components["schemas"]["PlateSet-Output"][];
            /**
             * Resistances
             * @default []
             */
            resistances: components["schemas"]["BandResistance"][];
        };
        /** EquipmentRead */
        EquipmentRead: {
            /** Code */
            code: string;
            /** Title Ru */
            title_ru: string;
            category: components["schemas"]["EquipmentCategory"];
            /** Supports Quantity */
            supports_quantity: boolean;
            /** Supports Weight List */
            supports_weight_list: boolean;
            /** Is Outdoor */
            is_outdoor: boolean;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Fields */
            fields?: {
                [key: string]: string;
            } | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /** ExerciseRead */
        ExerciseRead: {
            /** Slug */
            slug: string;
            /** Title Ru */
            title_ru: string;
            pattern_code: components["schemas"]["PatternCode"];
            /** Difficulty Level */
            difficulty_level: number;
            /** Is Unilateral */
            is_unilateral: boolean;
            /** Requires Pair */
            requires_pair: boolean;
            /** Is Quiet */
            is_quiet: boolean;
            /**
             * Required Equipment
             * @description AND of OR-groups of equipment codes; empty means bodyweight only
             */
            required_equipment: string[][];
            /** Primary Muscles */
            primary_muscles: components["schemas"]["Muscle"][];
            /** Needs Floor Space */
            needs_floor_space: boolean;
            /** Needs Ceiling Height */
            needs_ceiling_height: boolean;
            /** Lies On Floor */
            lies_on_floor: boolean;
            /** Secondary Muscles */
            secondary_muscles: components["schemas"]["Muscle"][];
            /** Contraindicated For */
            contraindicated_for: components["schemas"]["HealthTag"][];
            /** Technique Ru */
            technique_ru: string;
            /** Common Mistakes Ru */
            common_mistakes_ru: string[];
            /** Media */
            media: {
                [key: string]: string;
            };
            /** Prev Slug */
            prev_slug: string | null;
            /** Next Slug */
            next_slug: string | null;
            progression_criteria: components["schemas"]["ProgressionCriteria"] | null;
        };
        /** ExerciseSummary */
        ExerciseSummary: {
            /** Slug */
            slug: string;
            /** Title Ru */
            title_ru: string;
            pattern_code: components["schemas"]["PatternCode"];
            /** Difficulty Level */
            difficulty_level: number;
            /** Is Unilateral */
            is_unilateral: boolean;
            /** Requires Pair */
            requires_pair: boolean;
            /** Is Quiet */
            is_quiet: boolean;
            /**
             * Required Equipment
             * @description AND of OR-groups of equipment codes; empty means bodyweight only
             */
            required_equipment: string[][];
            /** Primary Muscles */
            primary_muscles: components["schemas"]["Muscle"][];
        };
        /**
         * Goal
         * @enum {string}
         */
        Goal: "hypertrophy" | "strength" | "endurance" | "fat_loss" | "skill" | "health" | "maintenance";
        /**
         * GuidanceLevel
         * @enum {string}
         */
        GuidanceLevel: "verbose" | "normal" | "quiet";
        /**
         * HealthTag
         * @enum {string}
         */
        HealthTag: "knees" | "shoulders" | "lower_back" | "wrists" | "neck" | "elbows";
        /** LadderRead */
        LadderRead: {
            pattern: components["schemas"]["PatternRead"];
            /**
             * Exercises
             * @description Ordered by difficulty_level
             */
            exercises: components["schemas"]["ExerciseSummary"][];
        };
        /** LocationCreate */
        LocationCreate: {
            kind: components["schemas"]["LocationKind"];
            /** Title */
            title: string;
            /**
             * Is Default
             * @default false
             */
            is_default?: boolean;
            /** Travel Minutes */
            travel_minutes?: number | null;
            /**
             * @default {
             *       "quiet_mode": false,
             *       "low_ceiling": false,
             *       "limited_space": false
             *     }
             */
            constraints?: components["schemas"]["Constraints-Input"];
        };
        /** LocationEquipmentIn */
        LocationEquipmentIn: {
            /** Equipment Code */
            equipment_code: string;
            /**
             * Quantity
             * @default 1
             */
            quantity?: number;
            /**
             * @default {
             *       "weights_kg": [],
             *       "plates": [],
             *       "resistances": []
             *     }
             */
            details?: components["schemas"]["EquipmentDetails-Input"];
        };
        /** LocationEquipmentRead */
        LocationEquipmentRead: {
            /** Equipment Code */
            equipment_code: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /**
             * @default {
             *       "weights_kg": [],
             *       "plates": [],
             *       "resistances": []
             *     }
             */
            details: components["schemas"]["EquipmentDetails-Output"];
        };
        /**
         * LocationKind
         * @enum {string}
         */
        LocationKind: "home" | "outdoor_gym" | "outdoor_bare" | "travel";
        /** LocationRead */
        LocationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["LocationKind"];
            /** Title */
            title: string;
            /** Is Default */
            is_default: boolean;
            /** Travel Minutes */
            travel_minutes: number | null;
            constraints: components["schemas"]["Constraints-Output"];
            /** Equipment */
            equipment: components["schemas"]["LocationEquipmentRead"][];
            /**
             * Available Exercise Count
             * @description Exercises doable here, given the equipment, constraints and health flags
             */
            available_exercise_count: number;
        };
        /** LocationUpdate */
        LocationUpdate: {
            /** Title */
            title?: string | null;
            /** Is Default */
            is_default?: boolean | null;
            /** Travel Minutes */
            travel_minutes?: number | null;
            constraints?: components["schemas"]["Constraints-Input"] | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Login
             * @description Email or username
             */
            login: string;
            /** Password */
            password: string;
        };
        /**
         * Muscle
         * @enum {string}
         */
        Muscle: "chest" | "front_delts" | "side_delts" | "rear_delts" | "triceps" | "biceps" | "forearms" | "lats" | "upper_back" | "lower_back" | "abs" | "obliques" | "glutes" | "quads" | "hamstrings" | "adductors" | "calves" | "hip_flexors";
        /**
         * Overall
         * @enum {string}
         */
        Overall: "beginner" | "intermediate" | "advanced";
        /** Page[UserRead] */
        Page_UserRead_: {
            /** Items */
            items: components["schemas"]["UserRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            readonly pages: number;
        };
        /** PasswordResetConfirm */
        PasswordResetConfirm: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * PatternCode
         * @enum {string}
         */
        PatternCode: "squat" | "hinge" | "push_h" | "push_v" | "pull_h" | "pull_v" | "lunge" | "carry" | "core" | "cardio";
        /** PatternLevelRead */
        PatternLevelRead: {
            pattern_code: components["schemas"]["PatternCode"];
            /** Estimated Level */
            estimated_level: number;
            /** Current Exercise Slug */
            current_exercise_slug: string;
            assessment_source: components["schemas"]["AssessmentSource"];
        };
        /** PatternLevelUpdate */
        PatternLevelUpdate: {
            pattern_code: components["schemas"]["PatternCode"];
            /** Estimated Level */
            estimated_level: number;
        };
        /** PatternRead */
        PatternRead: {
            code: components["schemas"]["PatternCode"];
            /** Title Ru */
            title_ru: string;
            /** Description Ru */
            description_ru: string;
            /** Is Bilateral Default */
            is_bilateral_default: boolean;
        };
        /**
         * Pistol
         * @enum {string}
         */
        Pistol: "no" | "assisted" | "yes";
        /** PlannedExerciseRead */
        PlannedExerciseRead: {
            /** Exercise Slug */
            exercise_slug: string;
            pattern_code: components["schemas"]["PatternCode"];
            /** Sets */
            sets: number;
            /** Target Min */
            target_min: number;
            /** Target Max */
            target_max: number;
            /**
             * Timed
             * @description target is seconds of work, not reps
             */
            timed: boolean;
            /** Rest Seconds */
            rest_seconds: number;
            /**
             * Rir
             * @description reps in reserve: stop the set this far from failure
             */
            rir: number;
            /**
             * Tempo
             * @description eccentric-pause-concentric, seconds
             */
            tempo: string | null;
        };
        /** PlannedSessionRead */
        PlannedSessionRead: {
            /**
             * Id
             * @description null in a preview
             */
            id: string | null;
            /** Day Index */
            day_index: number;
            /** Location Id */
            location_id: string | null;
            /** Title Ru */
            title_ru: string;
            /** Focus */
            focus: components["schemas"]["PatternCode"][];
            /** Estimated Minutes */
            estimated_minutes: number;
            /** Blocks */
            blocks: components["schemas"]["BlockRead"][];
        };
        /** PlateSet */
        "PlateSet-Input": {
            /** Kg */
            kg: number | string;
            /** Count */
            count: number;
        };
        /** PlateSet */
        "PlateSet-Output": {
            /** Kg */
            kg: string;
            /** Count */
            count: number;
        };
        /** PlatesRead */
        PlatesRead: {
            /** Target Kg */
            target_kg: string;
            /** Achievable */
            achievable: boolean;
            /**
             * Per Side
             * @description Plates for EACH side, heaviest first
             */
            per_side: components["schemas"]["PlateSet-Output"][];
            /**
             * Nearest Kg
             * @description Closest reachable weights when not achievable
             */
            nearest_kg: string[];
        };
        /** PlatesRequest */
        PlatesRequest: {
            /**
             * Equipment Code
             * @enum {string}
             */
            equipment_code: "barbell" | "dumbbell";
            /** Target Kg */
            target_kg: number | string;
        };
        /** ProfileRead */
        ProfileRead: {
            /** Birth Year */
            birth_year: number | null;
            goal_primary: components["schemas"]["Goal"] | null;
            goal_secondary: components["schemas"]["Goal"] | null;
            /** Days Per Week */
            days_per_week: number | null;
            /** Session Minutes */
            session_minutes: number | null;
            guidance_level: components["schemas"]["GuidanceLevel"];
            /** Health Flags */
            health_flags: components["schemas"]["HealthTag"][];
            /** Needs Medical Clearance */
            needs_medical_clearance: boolean;
            /** Medical Disclaimer Accepted At */
            medical_disclaimer_accepted_at: string | null;
            /**
             * Units
             * @enum {string}
             */
            units: "metric" | "imperial";
            /** Timezone */
            timezone: string;
            /** Onboarding Completed At */
            onboarding_completed_at: string | null;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Birth Year */
            birth_year?: number | null;
            goal_primary?: components["schemas"]["Goal"] | null;
            goal_secondary?: components["schemas"]["Goal"] | null;
            /** Days Per Week */
            days_per_week?: number | null;
            /** Session Minutes */
            session_minutes?: number | null;
            guidance_level?: components["schemas"]["GuidanceLevel"] | null;
            /** Health Flags */
            health_flags?: components["schemas"]["HealthTag"][] | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** ProgramDraft */
        ProgramDraft: {
            goal_primary: components["schemas"]["Goal"];
            structure: components["schemas"]["Structure"];
            /** Weeks Total */
            weeks_total: number;
            /** Rationale Ru */
            rationale_ru: string;
            /** Weeks */
            weeks: components["schemas"]["ProgramWeekRead"][];
        };
        /** ProgramRead */
        ProgramRead: {
            goal_primary: components["schemas"]["Goal"];
            structure: components["schemas"]["Structure"];
            /** Weeks Total */
            weeks_total: number;
            /** Rationale Ru */
            rationale_ru: string;
            /** Weeks */
            weeks: components["schemas"]["ProgramWeekRead"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["ProgramStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** ProgramRequest */
        ProgramRequest: {
            /**
             * Day Locations
             * @description Location for each training day, in order; all days at the default one if omitted
             */
            day_locations?: string[] | null;
        };
        /**
         * ProgramStatus
         * @enum {string}
         */
        ProgramStatus: "active" | "completed" | "abandoned";
        /** ProgramWeekRead */
        ProgramWeekRead: {
            /** Index */
            index: number;
            kind: components["schemas"]["WeekKind"];
            /** Volume Multiplier */
            volume_multiplier: number;
            /** Sessions */
            sessions: components["schemas"]["PlannedSessionRead"][];
        };
        /**
         * ProgressionCriteria
         * @description What to complete before moving to the next step, e.g. 3×12 or 3×30 s.
         */
        ProgressionCriteria: {
            /** Sets */
            sets: number;
            /** Reps */
            reps?: number | null;
            /** Hold Seconds */
            hold_seconds?: number | null;
        };
        /**
         * Pullups
         * @enum {string}
         */
        Pullups: "0" | "1-3" | "4-8" | "9-15" | "15+";
        /**
         * Pushups
         * @enum {string}
         */
        Pushups: "0" | "1-5" | "6-15" | "16-30" | "30+";
        /** SkillPrerequisite */
        SkillPrerequisite: {
            /** Exercise Slug */
            exercise_slug: string;
            /** Reps */
            reps?: number | null;
            /** Hold Seconds */
            hold_seconds?: number | null;
        };
        /** SkillRead */
        SkillRead: {
            /** Slug */
            slug: string;
            /** Title Ru */
            title_ru: string;
            /** Description Ru */
            description_ru: string;
            /** Prerequisites */
            prerequisites: components["schemas"]["SkillPrerequisite"][];
            /** Lead Up Exercise Slugs */
            lead_up_exercise_slugs: string[];
        };
        /**
         * Squats
         * @enum {string}
         */
        Squats: "<10" | "10-25" | "25-50" | "50+";
        /**
         * Structure
         * @enum {string}
         */
        Structure: "fullbody" | "upper_lower" | "ppl";
        /**
         * Surface
         * @enum {string}
         */
        Surface: "rubber" | "sand" | "asphalt";
        /**
         * TokenResponse
         * @description Access token only — the refresh token is set as an httpOnly cookie.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type?: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Full Name */
            full_name?: string | null;
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Full Name */
            full_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Is Superuser */
            is_superuser: boolean;
            /** Is Verified */
            is_verified: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Email */
            email?: string | null;
            /** Username */
            username?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Password */
            password?: string | null;
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            /** Token */
            token: string;
        };
        /**
         * WeekKind
         * @enum {string}
         */
        WeekKind: "accumulation" | "deload";
        /** WeightGrid */
        WeightGrid: {
            /** Equipment Code */
            equipment_code: string;
            /** Weights Kg */
            weights_kg: string[];
            /** Min Step Kg */
            min_step_kg: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    verify_email_api_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resend_verification_api_v1_auth_verify_email_resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    request_password_reset_api_v1_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirm_password_reset_api_v1_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserRead_"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_user_api_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_exercises_api_v1_exercises_get: {
        parameters: {
            query?: {
                pattern?: components["schemas"]["PatternCode"] | null;
                /** @description Equipment code the exercise uses; `none` for bodyweight only */
                equipment?: string | null;
                difficulty_min?: number | null;
                difficulty_max?: number | null;
                /** @description Only what's doable at this location of the signed-in user */
                location_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseSummary"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_exercise_api_v1_exercises__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_patterns_api_v1_patterns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternRead"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_ladder_api_v1_patterns__code__ladder_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["schemas"]["PatternCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LadderRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_equipment_api_v1_equipment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentRead"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_skills_api_v1_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillRead"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_profile_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_profile_api_v1_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    accept_disclaimer_api_v1_profile_disclaimer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisclaimerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    assess_api_v1_profile_assessment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_pattern_levels_api_v1_profile_pattern_levels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternLevelRead"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_pattern_levels_api_v1_profile_pattern_levels_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatternLevelUpdate"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternLevelRead"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    complete_onboarding_api_v1_profile_onboarding_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_locations_api_v1_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_location_api_v1_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_location_api_v1_locations__location_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_location_api_v1_locations__location_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    replace_equipment_api_v1_locations__location_id__equipment_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationEquipmentIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    weight_grid_api_v1_locations__location_id__weight_grid_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightGrid"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    plates_api_v1_locations__location_id__plates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatesRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview_program_api_v1_programs_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramDraft"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_program_api_v1_programs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    active_program_api_v1_programs_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_program_api_v1_programs__program_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
