"""add profiles, pattern levels and locations

Revision ID: b0598fc548b7
Revises: da22e7434976
Create Date: 2026-09-15 21:43:31.679715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0598fc548b7'
down_revision: Union[str, Sequence[str], None] = 'da22e7434976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('travel_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_user_id'), 'locations', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('birth_year', sa.SmallInteger(), nullable=True),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('goal_primary', sa.String(length=32), nullable=True),
    sa.Column('goal_secondary', sa.String(length=32), nullable=True),
    sa.Column('days_per_week', sa.SmallInteger(), nullable=True),
    sa.Column('session_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('guidance_level', sa.String(length=16), nullable=False),
    sa.Column('health_flags', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('needs_medical_clearance', sa.Boolean(), nullable=False),
    sa.Column('medical_disclaimer_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('units', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('location_equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_code', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_code'], ['equipment_items.code'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'equipment_code')
    )
    op.create_index(op.f('ix_location_equipment_location_id'), 'location_equipment', ['location_id'], unique=False)
    op.create_table('pattern_levels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pattern_code', sa.String(length=32), nullable=False),
    sa.Column('current_exercise_slug', sa.String(length=64), nullable=False),
    sa.Column('estimated_level', sa.Integer(), nullable=False),
    sa.Column('assessment_source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_exercise_slug'], ['exercises.slug'], ),
    sa.ForeignKeyConstraint(['pattern_code'], ['movement_patterns.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pattern_code')
    )
    op.create_index(op.f('ix_pattern_levels_user_id'), 'pattern_levels', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pattern_levels_user_id'), table_name='pattern_levels')
    op.drop_table('pattern_levels')
    op.drop_index(op.f('ix_location_equipment_location_id'), table_name='location_equipment')
    op.drop_table('location_equipment')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_locations_user_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
