"""add bodyweight share to exercises and goal to skills

Revision ID: 7b84f34fea25
Revises: 7c7c5afb987b
Create Date: 2026-09-16 16:32:45.045755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b84f34fea25'
down_revision: Union[str, Sequence[str], None] = '7c7c5afb987b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('bodyweight_share', sa.Numeric(precision=3, scale=2), server_default='0', nullable=False))
    op.add_column('skills', sa.Column('goal', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'goal')
    op.drop_column('exercises', 'bodyweight_share')
    # ### end Alembic commands ###
