"""add programs, program weeks and planned sessions

Revision ID: 943b40095244
Revises: b0598fc548b7
Create Date: 2026-09-15 22:40:46.699250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '943b40095244'
down_revision: Union[str, Sequence[str], None] = 'b0598fc548b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_primary', sa.String(length=32), nullable=False),
    sa.Column('structure', sa.String(length=16), nullable=False),
    sa.Column('weeks_total', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('generation_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale_ru', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_user_id'), 'programs', ['user_id'], unique=False)
    op.create_index('uq_programs_one_active_per_user', 'programs', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('program_weeks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('index', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('volume_multiplier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'index')
    )
    op.create_index(op.f('ix_program_weeks_program_id'), 'program_weeks', ['program_id'], unique=False)
    op.create_table('planned_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_week_id', sa.Uuid(), nullable=False),
    sa.Column('day_index', sa.SmallInteger(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('title_ru', sa.String(length=100), nullable=False),
    sa.Column('focus', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('estimated_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_week_id'], ['program_weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_week_id', 'day_index')
    )
    op.create_index(op.f('ix_planned_sessions_program_week_id'), 'planned_sessions', ['program_week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planned_sessions_program_week_id'), table_name='planned_sessions')
    op.drop_table('planned_sessions')
    op.drop_index(op.f('ix_program_weeks_program_id'), table_name='program_weeks')
    op.drop_table('program_weeks')
    op.drop_index('uq_programs_one_active_per_user', table_name='programs', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_programs_user_id'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
