"""add catalog tables

Revision ID: da22e7434976
Revises: 078f408fde08
Create Date: 2026-09-15 20:56:42.338563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da22e7434976'
down_revision: Union[str, Sequence[str], None] = '078f408fde08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_items',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title_ru', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('supports_quantity', sa.Boolean(), nullable=False),
    sa.Column('supports_weight_list', sa.Boolean(), nullable=False),
    sa.Column('is_outdoor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('movement_patterns',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title_ru', sa.String(length=100), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('is_bilateral_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('skills',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title_ru', sa.String(length=150), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lead_up_exercise_slugs', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title_ru', sa.String(length=150), nullable=False),
    sa.Column('pattern_code', sa.String(length=32), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('is_unilateral', sa.Boolean(), nullable=False),
    sa.Column('requires_pair', sa.Boolean(), nullable=False),
    sa.Column('is_quiet', sa.Boolean(), nullable=False),
    sa.Column('needs_floor_space', sa.Boolean(), nullable=False),
    sa.Column('needs_ceiling_height', sa.Boolean(), nullable=False),
    sa.Column('lies_on_floor', sa.Boolean(), nullable=False),
    sa.Column('required_equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_muscles', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('secondary_muscles', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('contraindicated_for', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('technique_ru', sa.Text(), nullable=False),
    sa.Column('common_mistakes_ru', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_slug', sa.String(length=64), nullable=True),
    sa.Column('next_slug', sa.String(length=64), nullable=True),
    sa.Column('progression_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pattern_code'], ['movement_patterns.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercises_pattern_level', 'exercises', ['pattern_code', 'difficulty_level'], unique=False)
    op.create_index('ix_exercises_required_equipment', 'exercises', ['required_equipment'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_exercises_slug'), 'exercises', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_slug'), table_name='exercises')
    op.drop_index('ix_exercises_required_equipment', table_name='exercises', postgresql_using='gin')
    op.drop_index('ix_exercises_pattern_level', table_name='exercises')
    op.drop_table('exercises')
    op.drop_table('skills')
    op.drop_table('movement_patterns')
    op.drop_table('equipment_items')
    # ### end Alembic commands ###
