"""add workout sessions, set logs and personal records

Revision ID: 7c7c5afb987b
Revises: 943b40095244
Create Date: 2026-09-16 11:37:20.309174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c7c5afb987b'
down_revision: Union[str, Sequence[str], None] = '943b40095244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('planned_session_id', sa.Uuid(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('readiness', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('substitutions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_tonnage_kg', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['planned_session_id'], ['planned_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_index('ix_workout_sessions_user_started', 'workout_sessions', ['user_id', 'started_at'], unique=False)
    op.create_index('uq_workout_sessions_one_in_progress_per_user', 'workout_sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'in_progress'"))
    op.create_table('set_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_uuid', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_slug', sa.String(length=64), nullable=False),
    sa.Column('pattern_code', sa.String(length=32), nullable=False),
    sa.Column('set_index', sa.SmallInteger(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('added_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('band', sa.String(length=32), nullable=True),
    sa.Column('reps', sa.SmallInteger(), nullable=False),
    sa.Column('tempo', sa.String(length=16), nullable=True),
    sa.Column('rir', sa.SmallInteger(), nullable=True),
    sa.Column('effort_label', sa.String(length=16), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_slug'], ['exercises.slug'], ),
    sa.ForeignKeyConstraint(['pattern_code'], ['movement_patterns.code'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid', name='uq_set_logs_client_uuid')
    )
    op.create_index(op.f('ix_set_logs_session_id'), 'set_logs', ['session_id'], unique=False)
    op.create_index('ix_set_logs_user_exercise_performed', 'set_logs', ['user_id', 'exercise_slug', 'performed_at'], unique=False)
    op.create_index('ix_set_logs_user_performed', 'set_logs', ['user_id', 'performed_at'], unique=False)
    op.create_table('personal_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_slug', sa.String(length=64), nullable=False),
    sa.Column('pattern_code', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('set_log_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_slug'], ['exercises.slug'], ),
    sa.ForeignKeyConstraint(['pattern_code'], ['movement_patterns.code'], ),
    sa.ForeignKeyConstraint(['set_log_id'], ['set_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_slug', 'kind')
    )
    op.create_index(op.f('ix_personal_records_user_id'), 'personal_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_records_user_id'), table_name='personal_records')
    op.drop_table('personal_records')
    op.drop_index('ix_set_logs_user_performed', table_name='set_logs')
    op.drop_index('ix_set_logs_user_exercise_performed', table_name='set_logs')
    op.drop_index(op.f('ix_set_logs_session_id'), table_name='set_logs')
    op.drop_table('set_logs')
    op.drop_index('uq_workout_sessions_one_in_progress_per_user', table_name='workout_sessions', postgresql_where=sa.text("status = 'in_progress'"))
    op.drop_index('ix_workout_sessions_user_started', table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    # ### end Alembic commands ###
