"""add body metrics, progress photos and skill progress

Revision ID: d605e50fed5e
Revises: 7b84f34fea25
Create Date: 2026-09-16 16:37:29.984107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd605e50fed5e'
down_revision: Union[str, Sequence[str], None] = '7b84f34fea25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waist_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('chest_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('hip_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('arm_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('thigh_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_body_metrics_user_measured', 'body_metrics', ['user_id', 'measured_at'], unique=False)
    op.create_table('progress_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('angle', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_progress_photos_user_taken', 'progress_photos', ['user_id', 'taken_at'], unique=False)
    op.create_table('skill_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_lead_up_slug', sa.String(length=64), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_slug'], ['skills.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_slug')
    )
    op.create_index(op.f('ix_skill_progress_user_id'), 'skill_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_progress_user_id'), table_name='skill_progress')
    op.drop_table('skill_progress')
    op.drop_index('ix_progress_photos_user_taken', table_name='progress_photos')
    op.drop_table('progress_photos')
    op.drop_index('ix_body_metrics_user_measured', table_name='body_metrics')
    op.drop_table('body_metrics')
    # ### end Alembic commands ###
