/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedLocationsRouteImport } from './routes/_authed/locations'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedWorkoutRouteImport } from './routes/_authed/workout'
import { Route as AuthedExercisesIndexRouteImport } from './routes/_authed/exercises/index'
import { Route as AuthedExercisesSlugRouteImport } from './routes/_authed/exercises/$slug'
import { Route as AuthedPatternsCodeRouteImport } from './routes/_authed/patterns/$code'
import { Route as AuthedProgramIndexRouteImport } from './routes/_authed/program/index'
import { Route as AuthedProgramNewRouteImport } from './routes/_authed/program/new'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLocationsRoute = AuthedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkoutRoute = AuthedWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExercisesIndexRoute = AuthedExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExercisesSlugRoute = AuthedExercisesSlugRouteImport.update({
  id: '/exercises/$slug',
  path: '/exercises/$slug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPatternsCodeRoute = AuthedPatternsCodeRouteImport.update({
  id: '/patterns/$code',
  path: '/patterns/$code',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProgramIndexRoute = AuthedProgramIndexRouteImport.update({
  id: '/program/',
  path: '/program/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProgramNewRoute = AuthedProgramNewRouteImport.update({
  id: '/program/new',
  path: '/program/new',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/locations': typeof AuthedLocationsRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/workout': typeof AuthedWorkoutRoute
  '/exercises/$slug': typeof AuthedExercisesSlugRoute
  '/patterns/$code': typeof AuthedPatternsCodeRoute
  '/program/new': typeof AuthedProgramNewRoute
  '/exercises/': typeof AuthedExercisesIndexRoute
  '/program/': typeof AuthedProgramIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/locations': typeof AuthedLocationsRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/workout': typeof AuthedWorkoutRoute
  '/': typeof AuthedIndexRoute
  '/exercises/$slug': typeof AuthedExercisesSlugRoute
  '/patterns/$code': typeof AuthedPatternsCodeRoute
  '/program/new': typeof AuthedProgramNewRoute
  '/exercises': typeof AuthedExercisesIndexRoute
  '/program': typeof AuthedProgramIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authed/locations': typeof AuthedLocationsRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/workout': typeof AuthedWorkoutRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/exercises/$slug': typeof AuthedExercisesSlugRoute
  '/_authed/patterns/$code': typeof AuthedPatternsCodeRoute
  '/_authed/program/new': typeof AuthedProgramNewRoute
  '/_authed/exercises/': typeof AuthedExercisesIndexRoute
  '/_authed/program/': typeof AuthedProgramIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/locations'
    | '/onboarding'
    | '/workout'
    | '/exercises/$slug'
    | '/patterns/$code'
    | '/program/new'
    | '/exercises/'
    | '/program/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/locations'
    | '/onboarding'
    | '/workout'
    | '/'
    | '/exercises/$slug'
    | '/patterns/$code'
    | '/program/new'
    | '/exercises'
    | '/program'
  id:
    | '__root__'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_authed/locations'
    | '/_authed/onboarding'
    | '/_authed/workout'
    | '/_authed/'
    | '/_authed/exercises/$slug'
    | '/_authed/patterns/$code'
    | '/_authed/program/new'
    | '/_authed/exercises/'
    | '/_authed/program/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/locations': {
      id: '/_authed/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthedLocationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workout': {
      id: '/_authed/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AuthedWorkoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/exercises/': {
      id: '/_authed/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof AuthedExercisesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/exercises/$slug': {
      id: '/_authed/exercises/$slug'
      path: '/exercises/$slug'
      fullPath: '/exercises/$slug'
      preLoaderRoute: typeof AuthedExercisesSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/patterns/$code': {
      id: '/_authed/patterns/$code'
      path: '/patterns/$code'
      fullPath: '/patterns/$code'
      preLoaderRoute: typeof AuthedPatternsCodeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/program/': {
      id: '/_authed/program/'
      path: '/program'
      fullPath: '/program/'
      preLoaderRoute: typeof AuthedProgramIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/program/new': {
      id: '/_authed/program/new'
      path: '/program/new'
      fullPath: '/program/new'
      preLoaderRoute: typeof AuthedProgramNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedLocationsRoute: typeof AuthedLocationsRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedWorkoutRoute: typeof AuthedWorkoutRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedExercisesSlugRoute: typeof AuthedExercisesSlugRoute
  AuthedPatternsCodeRoute: typeof AuthedPatternsCodeRoute
  AuthedProgramNewRoute: typeof AuthedProgramNewRoute
  AuthedExercisesIndexRoute: typeof AuthedExercisesIndexRoute
  AuthedProgramIndexRoute: typeof AuthedProgramIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedLocationsRoute: AuthedLocationsRoute,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedWorkoutRoute: AuthedWorkoutRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedExercisesSlugRoute: AuthedExercisesSlugRoute,
  AuthedPatternsCodeRoute: AuthedPatternsCodeRoute,
  AuthedProgramNewRoute: AuthedProgramNewRoute,
  AuthedExercisesIndexRoute: AuthedExercisesIndexRoute,
  AuthedProgramIndexRoute: AuthedProgramIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
